events {
    worker_connections 1024;
}

http {
    client_max_body_size 10M;

    upstream backend {
        server backend:8080;
    }

    # Теперь фронт — это статический nginx-контейнер на порту 80
    upstream frontend {
        server frontend:80;
    }

    server {
        listen 80;
        server_name _;

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 120s;
        }

        location /swagger-ui/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }

        location /v3/api-docs {
            proxy_pass http://backend;
            proxy_set_header Host $host;
        }

        # Статика фронта — без WebSocket, без upgrade
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}